#include<string>
#include "curl/curl.h"

using namespace std;
class TwitterHandler
{
    public:
         //Constructor
        TwitterHandler(string, string);     
        //Get tweets from one user, 0 for hardmob, 1 for adrenaline.   
        string GetTweetsFromUser(int,string);
        //Get tweets from hardmob and adrenaline
        void WriteAllTweets();
        //Read the file generated by WritePromoFile
        void ReadTweets(int = 1000);
        //Write all titles from tweets.
        void WritePromoFile(string, int=0 ,int = 0);
    private:
        static string _accessToken;
        const string filename = "posts.txt";
        string GetAccessToken(string ,string);
       
        CURL* _curl;
};